### PR TITLE
I was surprised to find these compiler-dependent keywords

### PR DESCRIPTION
**Pull request by aponigricon**
Maybe we should try Control-F'ing all these keywords in all of the source files?: http://msdn.microsoft.com/en-us/library/2e6a4at9(v=vs.80).aspx

### CODE REVIEW

**Comment by Ericson2314** [comment]
Oh haha. Check out https://github.com/Ericson2314/Voxlap/blob/conservative/include/porthacks.h :)

Ya did inspire me to clean up the trailing whitespace though

**Comment by aponigricon** [comment]
Oh... it's so dirty D:

But if it works fine then I guess I shouldn't bother...

**Comment by Ericson2314** [comment]
Well actually if ken only used assume(0) we can just abstract specific case more like you did. Also Cajun had an idea to sub for builtin_unreachable for the gcc version that don't support it.

**Comment by Ericson2314** [comment]
Aha! he only uses assume(0) (got to love grep -r for these things). If you want to make like an UNREACHABLE_PORTABLE macro (feel free to think of a shorter, better name). I'll be happy to rebase it.

**Comment by aponigricon** [comment]
``` C
#if GCC_VERSION >= 40500
    #define _gtfo (__builtin_unreachable();)
#elif _MSC_VER >= 1310
    #define _gtfo (__assume(0);)
#endif
```

???

Oh, do you mean that I should do that instead myself? K.

**Comment by aponigricon** [comment]
wait a fucking second D:
how the hell did I commit that??? D: D: D:
**UNDO UNDO**

**Comment by aponigricon** [comment]
Oh, wait... I didn't commit anything into the base repo?...

*sigh*   I have failed to understand Github and Git completely, haven't I?

**Comment by Cajun-Style** [comment]
Why would this be better than what we already had...?

**Comment by Ericson2314** [comment]
Just a bit more succinct as ken always used assume(0) and not another condition. I feel this should work better with your pre- builtin_unreachable alternatives too, Cajun (which i need to merge and will do right now).

**Comment by Ericson2314** [comment]
Also Cajun, see what is actually commited, not what was in this pull request.

**Pull request merged**
