### PR TITLE
Changed _asm to __asm

### PR DESCRIPTION
**Pull request by aponigricon**
Two underscores, mate ;)

http://msdn.microsoft.com/en-us/library/4ks26t93(v=vs.71).aspx

### CODE REVIEW

**Comment by Ericson2314** [comment]
http://msdn.microsoft.com/en-us/library/45yd4tzz%28v=vs.71%29.aspx "For compatibility with previous versions, _asm is a synonym for __asm."

Do you think it's still better form to use two? If so I'll do a regex to replace EVERY instance of assembly in all files (all the MSVC ones are a single underscore ATM). Initially I left in in just to make merging if ken did something upstream easier, but that's unlikely to happen.

**Comment by aponigricon** [comment]
> http://msdn.microsoft.com/en-us/library/45yd4tzz%28v=vs.71%29.aspx "For compatibility with previous versions,
> _asm is a synonym for __asm."

The MSDN reference entry you're linking to was written for Visual Studio 2003. And what compiler was the original Voxlap written for? (Hint: MSVC 6.0... also known as Visual C/C++ 2003)
**...**
What a coincidence, right?

> Do you think it's still better form to use two? If so I'll do a regex to replace EVERY instance of assembly in all files (all 
> the MSVC ones are a single underscore ATM). Initially I left in in just to make merging if ken did something upstream 
> easier, but that's unlikely to happen.

Short answer: Yes. For the first, all the "previous versions" won't be able to compile Voxlap nor this port of Voxlap anyway. For the second, Microsoft seems to encourage developers to use `__asm` instead of `_asm`. Soo... the answer should be fairly clear. _But of course, if it makes something easier to simply leave the `_asm`'s as they are, then I can't see any good arguments against that_
But I'm not gonna lie; I honestly didn't notice that part of the entry ^_^

**Comment by aponigricon** [comment]
PS: Apparently I did something in Git which made GitHub close this pull request... I assume we can still disscuss `__asm` vs. `_asm` here...

**Comment by Ericson2314** [comment]
http://msdn.microsoft.com/en-us/library/45yd4tzz%28v=vs.110%29.aspx I think MS basically has ignored inline assembly, from 2003-2012 they had the same approach of allowing _asm but recommending __asm.

I'm also pretty sure you could compile this with older versions too seeing this is not an issue. If there is another reason I'd love to here it though.

Seeing all that I don't think this matters much, but I'd change if you still think it's worth it.

**Comment by aponigricon** [comment]
Before you do anything let's look at the pros and cons for switching to __asm:
Pros:
- Recommended by Microsoft.
- The older compilers that support "_asm" won't really be able to compile Voxlap anyways. (And yes, I know this for sure)

Cons:
- "_asm" is supported in older compilers.
- Using "_asm" instead makes the compatibility much more flexible... yet unnecessary.

2 pros minus 2 cons equals 0. Soo I assume that means it doesn't matter at all.

But that means something else too: It doesn't matter if we use __asm or _asm. I assume we can even use them together. Soo... we might just keep using _asm without replacing anything, and just use one of the directives as we like.

**Comment by Ericson2314** [comment]
Sounds like a plan. I am curious though, what makes you sure the old compilers will not work? Honest question, I only thought it would work because I didn't think I had used too many MSVC features radically different than ken's version of Voxlap, but I certainly could be wrong.

**Comment by aponigricon** [comment]
Ken implied himself in the original readme that older VC compilers wouldn't compile Voxlap.
...actually let me make a quick comment on that line in the readme...

**EDIT:**

> Apparently we can't make line commentss in .txt files, but Ken's implication is on line 286, in the requirements section.

**Comment by Ericson2314** [comment]
Oh, I see. Well if it at least compiles with MSVC 2003, I'll say that's enough legacy support. :)

**Pull request closed without merging**
